#!/usr/bin/env python3
"""
Interactive probability calculation demonstration
Shows step-by-step how AND/OR gates and links are calculated
"""

def demonstrate_calculations():
    """Demonstrate probability calculations with detailed explanations"""
    
    print("="*80)
    print("FTA EDITOR PROBABILITY CALCULATION DEMONSTRATION")
    print("="*80)
    print()
    
    # Example 1: AND Gate
    print("Example 1: AND Gate with Children")
    print("-" * 80)
    print("Scenario:")
    print("  Parent node: base_probability = 0.8, logicGate = 'AND'")
    print("  Child 1: probability = 0.5")
    print("  Child 2: probability = 0.4")
    print()
    print("Formula: base_prob × ∏(child_probs)")
    print("Calculation:")
    print("  Step 1: Product of children = 0.5 × 0.4 = 0.2")
    print("  Step 2: Multiply by base = 0.8 × 0.2 = 0.16")
    print("  Result: 0.16")
    print()
    print("Interpretation: All events must occur together (intersection)")
    print()
    
    # Example 2: OR Gate
    print("Example 2: OR Gate with Children")
    print("-" * 80)
    print("Scenario:")
    print("  Parent node: base_probability = 1.0, logicGate = 'OR'")
    print("  Child 1: probability = 0.5")
    print("  Child 2: probability = 0.4")
    print()
    print("Formula: 1 - ∏(1 - child_prob)")
    print("Calculation:")
    print("  Step 1: Convert to failure probs = (1-0.5), (1-0.4) = 0.5, 0.6")
    print("  Step 2: Product of failures = 0.5 × 0.6 = 0.3")
    print("  Step 3: Complement = 1 - 0.3 = 0.7")
    print("  Result: 0.7")
    print()
    print("Interpretation: At least one event occurs (union)")
    print()
    
    # Example 3: AND Link
    print("Example 3: AND Link Between Nodes")
    print("-" * 80)
    print("Scenario:")
    print("  Node A: probability = 0.8")
    print("  Node B: probability = 0.6")
    print("  Node A has AND link to Node B")
    print()
    print("Formula: current_prob × linked_prob")
    print("Calculation:")
    print("  Node B probability = 0.6 (calculated first)")
    print("  Node A with AND link = 0.8 × 0.6 = 0.48")
    print("  Result: Node A = 0.48")
    print()
    print("Interpretation: Both Node A and Node B must occur")
    print()
    
    # Example 4: OR Link
    print("Example 4: OR Link Between Nodes")
    print("-" * 80)
    print("Scenario:")
    print("  Node A: probability = 0.5")
    print("  Node B: probability = 0.3")
    print("  Node A has OR link to Node B")
    print()
    print("Formula: 1 - (1-prob_A) × (1-prob_B)")
    print("Calculation:")
    print("  Node B probability = 0.3 (calculated first)")
    print("  Step 1: Failure probs = (1-0.5), (1-0.3) = 0.5, 0.7")
    print("  Step 2: Product = 0.5 × 0.7 = 0.35")
    print("  Step 3: Complement = 1 - 0.35 = 0.65")
    print("  Result: Node A = 0.65")
    print()
    print("Interpretation: Either Node A or Node B (or both) occurs")
    print()
    
    # Example 5: Mixed AND and OR Links
    print("Example 5: Mixed AND and OR Links")
    print("-" * 80)
    print("Scenario:")
    print("  Node A: base probability = 0.5")
    print("  Node B: probability = 0.8")
    print("  Node C: probability = 0.4")
    print("  Node A has AND link to Node B and OR link to Node C")
    print()
    print("Processing order: AND links first, then OR links")
    print("Calculation:")
    print("  Step 1: Calculate Node B and C (0.8 and 0.4)")
    print("  Step 2: Apply AND link to B: 0.5 × 0.8 = 0.4")
    print("  Step 3: Apply OR link to C: 1 - (1-0.4)×(1-0.4)")
    print("         = 1 - 0.6×0.6 = 1 - 0.36 = 0.64")
    print("  Result: Node A = 0.64")
    print()
    print("Interpretation: (A AND B) OR C")
    print()
    
    # Example 6: Nested Gates
    print("Example 6: Nested AND Gates")
    print("-" * 80)
    print("Scenario:")
    print("  Root: base_prob = 1.0, AND gate")
    print("    └─ Child: base_prob = 0.9, AND gate")
    print("        ├─ GrandChild1: prob = 0.5")
    print("        └─ GrandChild2: prob = 0.6")
    print()
    print("Calculation (bottom-up):")
    print("  Step 1: GrandChild1 = 0.5 (leaf)")
    print("  Step 2: GrandChild2 = 0.6 (leaf)")
    print("  Step 3: Child = 0.9 × (0.5 × 0.6) = 0.9 × 0.3 = 0.27")
    print("  Step 4: Root = 1.0 × 0.27 = 0.27")
    print("  Result: Root = 0.27")
    print()
    
    # Example 7: Real-world scenario
    print("Example 7: Real-World FTA Scenario")
    print("-" * 80)
    print("System Failure Analysis:")
    print("  System fails if: (Component A fails AND Component B fails)")
    print("                   OR (Component C fails)")
    print()
    print("Tree Structure:")
    print("  System [OR gate, base_prob=1.0]")
    print("    ├─ Subsystem1 [AND gate, base_prob=1.0]")
    print("    │   ├─ Component A [prob=0.1 (10% failure)]")
    print("    │   └─ Component B [prob=0.2 (20% failure)]")
    print("    └─ Component C [prob=0.05 (5% failure)]")
    print()
    print("Calculation:")
    print("  Component A = 0.1 (leaf)")
    print("  Component B = 0.2 (leaf)")
    print("  Subsystem1 (AND) = 1.0 × (0.1 × 0.2) = 1.0 × 0.02 = 0.02")
    print("  Component C = 0.05 (leaf)")
    print("  System (OR) = 1 - (1-0.02)×(1-0.05)")
    print("              = 1 - 0.98×0.95 = 1 - 0.931 = 0.069")
    print("  Result: System failure probability = 0.069 (6.9%)")
    print()
    print("Interpretation: 6.9% chance of system failure")
    print()
    
    print("="*80)
    print("KEY TAKEAWAYS")
    print("="*80)
    print("1. AND gate: P(A∩B) = P(A) × P(B) - events must all occur")
    print("2. OR gate: P(A∪B) = 1 - (1-P(A))×(1-P(B)) - at least one occurs")
    print("3. AND links: Multiply probabilities (intersection)")
    print("4. OR links: Apply union formula (at least one)")
    print("5. Processing order: Children → AND links → OR links")
    print("6. Calculation is bottom-up (leaves first, then parents)")
    print("="*80)
    print()


if __name__ == "__main__":
    demonstrate_calculations()
